### ISSUE TITLE
Review: NavBar Component & Landing Page

### ISSUE THREAD

**Issue by RaphaelBumanlag** [ohana-volunteers/ohana-volunteers#23]
## Overview

For our first review, we're going to take a look at Navbar Component and the Landing page.

## Review Branch

review-001

## Files to review

* [NavBar.jsx](https://github.com/ohana-volunteers/ohana-volunteers/blob/review-001/app/imports/ui/components/NavBar.jsx)
* [Landing.jsx](https://github.com/ohana-volunteers/ohana-volunteers/blob/review-001/app/imports/ui/pages/Landing.jsx)

## Checklists

* [Architecture](https://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-architecture-checklist)
* [Design](https://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-design-checklist)
* [JS](https://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-js-checklist)
* [Testing](https://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-testing-checklist)

## Due date

Tuesday, February 1

## For more information

The review process is documented at: https://courses.ics.hawaii.edu/ics414s22/morea/review/reading-idpm-review.html

**Comment by joshipaino** [comment]
NavBar.jsx:
L7-8: DE-03: Unused/commented-out imports.
L21-69: TI-01: Missing component id's for isDisplayed() tests of linked pages.

Landing.jsx:
L203-211: DE-01: Same code present in AboutsUs.jsx and PrivacyPolicy.jsx. Can be made into a component.
L73-136: DE-01: Duplicated cards can be made into a component (once associated collection is created).

**Comment by cammoore** [comment]
## NavBar.jsx

DE-04: L7,8: Get rid of commented out code.

L34-39: Are there different NavBars for the different roles? If so
then the name of this file is missleading.

DE-07: L43-69: Should this be a component?

## Landing.jsx

DE-07: L76-89: This should be a component that we import and
instantiate.  

DE-07: L144-146: This should be a component that we import and
instantiate.

**Comment by RaphaelBumanlag** [comment]
NavBar.jsx
L7-8: DE-05: Remove commented out code

**Comment by yongxinyang** [comment]
E-05: add necessary comment

DE-01: 
Since all card have the same format, we can probably keep one and retrieve data to fill it in the future

**Comment by believeinlain** [comment]
I haven't done the review yet, sorry - working on it.

**Comment by chowc89** [comment]
Landing.jsx:
The background is empty, can add some image to it.
