### ISSUE TITLE
Review: Organization Profile and Volunteer Profile Pages

### ISSUE THREAD

**Issue by joshipaino** [ohana-volunteers/ohana-volunteers#32]
## Overview

The focus for this code review will be centered around the Organization Profile and Volunteer Profile pages.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-002

## Files to review

* [OrganizationProfile.jsx](https://github.com/ohana-volunteers/ohana-volunteers/blob/review-002/app/imports/ui/pages/OrganizationProfile.jsx)
* [VolunteerProfile.jsx](https://github.com/ohana-volunteers/ohana-volunteers/blob/review-002/app/imports/ui/pages/VolunteerProfile.jsx)

## Checklists

* [Architecture](https://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-architecture-checklist)
* [Design](https://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-design-checklist)
* [JS](https://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-js-checklist)
* [React](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-react-checklist)
* [Testing](https://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-testing-checklist)

## Due date

Tuesday, February 8

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by believeinlain** [comment]
## OrganizationProfile.jsx
DE-05: L10: comment mentions landing page

## VolunteerProfile.jsx
TA-01: No corresponding file in tests folder for isDisplayed test

**Comment by joshipaino** [comment]
### OrganizationProfile.jsx
L16: Will the admins be controlling/publishing the organization profiles or will the organization themselves be handling it?
L20: DE-05: Comment describes the rendering text for the landing page despite the file being the OrganizationProfile page.
L57: TA-01: Provide component ID for "Edit Profile button" (once the Edit Profile page has been created).

### VolunteerProfile.jsx
L46-115: DE-01: Can the cards that present volunteer information be moved into a component?
L57: TA-01: Provide component ID for "Edit button" (once the Edit Profile page has been created).  Also, will the button be visible to those who are not the owner of the profile?

**Comment by yongxinyang** [comment]
**Organization Profile:**
UI-01: L16: the owner is ‘admin’ for all instances?

**Volunteer Profile:**
DE-07:  Should this be a component?
DE-04: L14, 16, 36,39,42,44,119: properly get rid of some blank lines?
RE-04: L98-99: Environmental Preference has only a single choice

**Comment by chowc89** [comment]
OrganizationProfile.jsx
L25: Should we add a href to the address, so when people clicks on it, it leads to the map showing that address?
DE-05: L10: Change the comment.
L50: Should the Edit profile button only show to the owner?

Volunteer Profile:
L32: Should the Edit profile button only show to the owner?
Remove unnecessary Blank lines.

**Comment by cammoore** [comment]
## OrganizationProfile.jsx

L21: Pass in the testOrg as a parameter. This will help when you hook
it up to a collection.

L57: Might want to have a dummy handleClick function. Again it will
help when you actually have the ability to edit.

## VolunteerProfile.jsx

L8: Might want to pass in a dummy volunteerProfile object. This will
help when you hook it up to the collection. Think about what you want
in your VolunteerProfileCollection.

L9: Why use a grid? When all it has is a single card.

L32: Might want to have a dummy handleClick function. Again it will
help when you actually have the ability to edit.

**Comment by RaphaelBumanlag** [comment]
### OrganizationProfile.jsx
L10: Turn card into component, pass information through from collections.

### VolunteerProfile.jsx
L10: Turn card into component, pass information through from collections

**Comment by believeinlain** [comment]
Corrected issues in OrganizationProfile.jsx and pushed changes to branch review-002

**Comment by believeinlain** [comment]
@joshipaino please make whatever changes are necessary in VolunteerProfile.jsx from the review comments so that we can merge review-002 back to main
